### ISSUE TITLE
Failed to resolve: com.afollestad:easyvideoplayer:0.2.2

### ISSUE THREAD

**Issue by easycheese** [afollestad/easy-video-player#1]
Error:(99, 13) Failed to resolve: com.afollestad:easyvideoplayer:0.2.2
<a href="openFile:C:/Users/kyles/Documents/Bitbucket/photo-frame/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Any idea what's up?  I tried the other versions as well....

**Comment by afollestad** [comment]
Something odd is going on with jCenter, but you can reference the Bintray repository directly.

Add this to your `repositories { }`: 

```gradle
    maven { url "https://dl.bintray.com/drummer-aidan/maven" }
```

**Comment by easycheese** [comment]
That did it but then I realized the minSDK is 14 :(

**Comment by yipengmu** [comment]
useful

**Comment by ch-muhammad-adil** [comment]
Hey please update your Read me file regarding maven . I was also facing same issue.

**Comment by piyushgreedy** [comment]
Please tell how to resolve step by step. I am new to android

Error:(31, 13) Failed to resolve: com.afollestad:easyvideoplayer:0.2.10.0
