### ISSUE TITLE
Gradle dependency not able to compile

### ISSUE THREAD

**Issue by abhishekjain885** [afollestad/easy-video-player#19]
Error:(27, 13) Failed to resolve: com.afollestad:easyvideoplayer:0.2.9
<a href="openFile:D:/android/Facebook-Feed-Sample-master/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Maragues** [comment]
I'm also seeing this error. Gradle is trying to resolve this paths, which don't exist

```
Could not find com.afollestad:easyvideoplayer:0.2.9.
Searched in the following locations:
   https://jcenter.bintray.com/com/afollestad/easyvideoplayer/0.2.9/easyvideoplayer-0.2.9.pom
   https://jcenter.bintray.com/com/afollestad/easyvideoplayer/0.2.9/easyvideoplayer-0.2.9.jar
```

The project does exist in jcenter (https://bintray.com/drummer-aidan/maven/easy-video-player/0.2.9), but there must be a routing error

**Comment by afollestad** [comment]
A temp solution is already in an existing issue.

https://github.com/afollestad/easy-video-player/issues/1
