### ISSUE TITLE
Audio not exposed

### ISSUE THREAD

**Issue by easycheese** [afollestad/easy-video-player#2]
Can't set the volume or get the mediaplayer to set the volume.

**Comment by afollestad** [comment]
I don't plan to add controls for that. The system already manages volume for ringtones, media, etc. separately from the volume menu.

**Comment by easycheese** [comment]
I disagree, see the doc:

http://developer.android.com/intl/pt-br/reference/android/media/MediaPlayer.html#setVolume(float, float)

The mediaplayer.setVolume method should be used in preference to the global settings.
