### ISSUE TITLE
play at specific second

### ISSUE THREAD

**Issue by silverboyir** [afollestad/easy-video-player#24]
Hi
i want to start play video at a specific second (second 3)
i set the autoplay to false and in onPrepared set player.seekTo(3000); 
but its not work in any case (also tries inside of Timer in this method too)
it always start from start (my video has 22 second length so cant be problem from here)

also how i can pause or stop video , when my app will be send to background by user ?

Thanks for your great library

**Comment by chaeMil** [comment]
Hi. you can pause or resume the player with player.pause() and player.stop() and player.start()...

To start if from some time use player.setInitialPosition(yourTimeInInt);
