### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mathiasi** [afollestad/easy-video-player#30]
I have tried to install easy video player using the Gradle dependency on two separate computers and one of them happened to be a completely fresh installation but in both instances the Gradle build would fail because it was unable to resolve the dependency. 
I have added 

    compile 'com.afollestad:easyvideoplayer:0.2.9

as per the instructions.
The only way I could get it to work was to go to https://bintray.com/drummer-aidan/maven/easy-video-player/0.2.9# and download the .aar and .pom file and install it manually to my local Maven repo using

    mvn install:install-file -Dfile=easyvideoplayer-0.2.9.aar -DpomFile=easyvideoplayer-0.2.9.pom

and add 

    repositories {
        mavenLocal()
    }
to my buildscript.
I feel like the installation instructions are wrong or outdated and should probably be verified. But now that I got it to work, thanks for a handy piece of library :)

**Comment by rajeshgoswami2025** [comment]
Facing same described problem, Author please help us to install the easy video player using gradle.

**Comment by afollestad** [comment]
Read the duplicate closed issues
