### ISSUE TITLE
Using Player in RecyclerView

### ISSUE THREAD

**Issue by BeBetter7** [afollestad/easy-video-player#32]
I use this player in RecyclerView. But I'm facing two problems. 

First, I can only load three videos. Then the other videos don't load.
Second, one video is loading. I can play it. I scroll recyclerview down and when I returned to loaded video, player is null.

What can cause this problem?

**Comment by vedo1608** [comment]
bump, having the same issue, it's something with recycling the views and not recreating them properly, but I can't get it to work

**Comment by halilozercan** [comment]
Using dynamic loaded views in recyclerview or any other listview for that matter is not a good pratice in general. However, recyclerview makes it easy to implement workarounds.

onBindViewHolder is where the magic happens. Whenever the view leaves the screen, it gets destroyed. If it comes on the screen again, onBindViewHolder is called again. So, probably EasyVideoPlayer does not survive after leaving the screen and it really shouldn't anyway. 

My suggestion would be to pause the video. Save the state somewhere. When onBindViewHolder called once again, you restore the saved state and move on.
