### ISSUE TITLE
Hello,I use compile method to load easy-video-player in android studio.However,I fialed.Is it anything changing for load easy-video-player.How can I do to compile this in android studio?

### ISSUE THREAD

**Issue by RiverLi99** [afollestad/easy-video-player#36]
Error:Failed to resolve: com.afollestad.easyvideoplayer:0.2.10:
<a href="openFile:F:/AndroidStudioProject/EasyVideoPlayer/app/build.gradle">Open File</a>

**Comment by arsikj** [comment]
I have the same issue

**Comment by afollestad** [comment]
https://github.com/afollestad/easy-video-player/issues/34
