### ISSUE TITLE
Video stuck on first frame

### ISSUE THREAD

**Issue by saadnawaz1** [afollestad/easy-video-player#37]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Easy Video Player.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).
###### Include the following:
- Easy Video Player version: `0.2.10`
- Device OS version: `6.0.1` (CM 13)
- Device Manufacturer: `HTC`
- Device Name: `One m8`

Also, please wrap Java with correct syntax highlighting.
**no exception**
###### Reproduction Steps
1.  My project has compileSdkVersion 23 and minSdkVersion of 16 and targetSdkVersion of 22. The player is inside a LinearLayout and following is the code:

```

<com.afollestad.easyvideoplayer.EasyVideoPlayer
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            android:id="@+id/my_video_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_gravity="center"
            app:evp_autoFullscreen="true"
            app:evp_disableControls="true"
            app:evp_hideControlsOnPlay="true"
            android:gravity="center"/>

```
1.  Now, programmatically I am setting the source to a local mp4 file via 

`this.myVideoView.setSource(Uri.parse(localVideoPath));`
1. Upon onPrepared callback, I do following

`this.myVideoView.start();`

At this point no exception/error is thrown
###### Expected Result

Video plays
###### Actual Result

Video gets stuck on the first frame and doesn't play

**Comment by ingsaurabh** [comment]
same here

**Comment by Raykud** [comment]
@saadnawaz1 how are you setting your localVideoPath?

**Comment by afollestad** [comment]
I haven't experienced this, and there have been a few newer releases, so I'm going to assume this no longer happens.

**Comment by sjd753** [comment]
Issue reproduced video stutters and stuck on frame from url
