### ISSUE TITLE
Can not find the library through Gradle

### ISSUE THREAD

**Issue by zunjae** [afollestad/easy-video-player#38]
- [N ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y] I have verified that I am using the latest version of Easy Video Player.
- [Y] I have given my issue a non-generic title.
- [N] I have read over the documentation (before asking questions on how to do something).

I am getting this error

Error:Could not find com.afollestad:easyvideoplayer:0.2.10.
Required by:
mal:app:unspecified

just to let you know, this does not happen on any other library that I add

**Comment by zunjae** [comment]
Nevermind, updating Android Support Repository fixed this issue

**Comment by Murtaza0xFF** [comment]
Seems like updating the Android Support Repository isn't the fix. It didn't work for me, at least.

**Comment by zunjae** [comment]
Have you tried adding this url to your repositories?

maven { url "https://dl.bintray.com/drummer-aidan/maven" }
