### ISSUE TITLE
Failed to resolve: com.afollestad:easyvideoplayer:0.2.10.0

### ISSUE THREAD

**Issue by piyushgreedy** [afollestad/easy-video-player#39]
Please tell how to resolve step by step. I am new to android

Error:(31, 13) Failed to resolve: com.afollestad:easyvideoplayer:0.2.10.0

**Comment by zunjae** [comment]
add this url to your repository

maven { url "https://dl.bintray.com/drummer-aidan/maven" }

and update your Android Support Repository

**Comment by piyushgreedy** [comment]
could you please add a screenshot. where to add. i am new to android.
Please ..

**Comment by zunjae** [comment]
In your build.gradle file just look for repository and add it there.

By default it will look like this

`repositories {
    maven {
        url "https://jitpack.io"
    }
    mavenCentral()
}`

**Comment by Murtaza0xFF** [comment]
@zunjae  that doesn't solve the issue.

**Comment by afollestad** [comment]
@zunjae just so you know, you use three ``` symbols for multi-line syntax highlighting ;)

**Comment by piyushgreedy** [comment]
I have attached the screenshot.Please tell where to add.....
Please...

**Comment by afollestad** [comment]
@piyushgreedy you can't attach images via email on GitHub, you have to go to the issue page.

You put it in build.gradle under allprojects, we can't teach you everything about Android Studio here.

**Comment by afollestad** [comment]
![capture](https://cloud.githubusercontent.com/assets/1820165/18099722/88f7851e-6ead-11e6-9288-45d944c0be94.JPG)
