### ISSUE TITLE
Dynamically change source of video

### ISSUE THREAD

**Issue by chaeMil** [afollestad/easy-video-player#48]
- Easy Video Player version: `0.2.12`
- Device OS version: `7.0`
- Device Manufacturer: `LG`
- Device Name: `Nexus 5X`

When i use `player.setSource( ... );` on already running player, nothing happens
###### Expected Result

Change the source file and start buffering
###### Actual Result

Nothing changes

There's no problem with this on stock Android VideoView.

**Comment by CHPraxis** [comment]
Not the developer, but the documentation says that you should call player.reset() before setting a new source...
