### ISSUE TITLE
Set drawable for submit button

### ISSUE THREAD

**Issue by theAliAkhgar** [afollestad/easy-video-player#49]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Easy Video Player.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).
###### Include the following:
- Easy Video Player version: `0.2.12`
- Device OS version: `6.0`
- Device Manufacturer: `GenyMotion`

Hi, I was hoping if you can make a quick implemention from you to your library, I wanted to be able to set drawable for the submit button, i truly need it.

thanks for you good library

**Comment by afollestad** [comment]
I intend to keep it as text.
