### ISSUE TITLE
add EasyVideoPlayer  dynamic

### ISSUE THREAD

**Issue by abbasalim** [afollestad/easy-video-player#50]
hello. i user below code for add EasyVideoPlayer  Dynamically:

`EasyVideoPlayer  s = new EasyVideoPlayer(ReadActivity.this);
                            s.setSource(Uri.parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"));
//                            s.setMediaController(new MediaController(ReadActivity.this));
                            LinearLayout.LayoutParams llParams = new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,Utils.dpToPx(250));
                            s.setLayoutParams(llParams);

                            s.setCallback(new EasyVideoCallback() {
                                @Override
                                public void onStarted(EasyVideoPlayer player) {
                                    Log.d("MOHSEN Video", "onStarted");
                                }

                                @Override
                                public void onPaused(EasyVideoPlayer player) {
                                    Log.d("MOHSEN Video", "onPaused");
                                }

                                @Override
                                public void onPreparing(EasyVideoPlayer player) {
                                    Log.d("MOHSEN Video", "onPreparing");
                                }

                                @Override
                                public void onPrepared(EasyVideoPlayer player) {
                                    Log.d("MOHSEN Video", "onPrepared");
                                }

                                @Override
                                public void onBuffering(int percent) {
                                    Log.d("MOHSEN Video", "onBuffering");
                                }

                                @Override
                                public void onError(EasyVideoPlayer player, Exception e) {
                                    Log.d("MOHSEN Video", "onError");
                                    e.printStackTrace();
                                }

                                @Override
                                public void onCompletion(EasyVideoPlayer player) {
                                    Log.d("MOHSEN Video", "onCompletion");
                                }

                                @Override
                                public void onRetry(EasyVideoPlayer player, Uri source) {
                                    Log.d("MOHSEN Video", "onRetry");
                                }

                                @Override
                                public void onSubmit(EasyVideoPlayer player, Uri source) {
                                    Log.d("MOHSEN Video", "onSubmit");
                                }
                            });
                            s.start();
                            ll.addView(s);`

but show me a black screen and no work:
[http://www.axgig.com/images/05375083812515760360.png](url)

**Comment by theAliAkhgar** [comment]
try adding the view and then calling start() method, it might work!
