### ISSUE TITLE
Library Gradle Sync issue

### ISSUE THREAD

**Issue by Lalit-ETT** [afollestad/easy-video-player#52]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Easy Video Player.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `x.x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by amitMist** [comment]
You need to add in your project's build.gradle. Should look like this -
`allprojects {
    repositories {
        jcenter()
        maven { url "https://dl.bintray.com/drummer-aidan/maven" }
    }
}`

**Comment by Lalit-ETT** [comment]
I did the same but issue is still remain
Thanks & Regards 
Lalit Goswami
Associate Software Engineer
RationalHeads Technologies Pvt. Ltd.

---- On Tue, 13 Sep 2016 04:51:42 +0530 notifications@github.com wrote ----

You need to add in your project's build.gradle. Should look like this -
allprojects {
repositories {
jcenter()
maven { url "https://dl.bintray.com/drummer-aidan/maven" }
}
}

**Comment by wdmxzf** [comment]
I compile 'com.afollestad:easyvideoplayer:0.2.12' is failed；

**Comment by afollestad** [comment]
Duplicate.
