### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class android.media.MediaPlayer   at com.afollestad.easyvideoplayer.EasyVideoPlayer.onFinishInflate(EasyVideoPlayer.java:714)

### ISSUE THREAD

**Issue by FDMpro** [afollestad/easy-video-player#56]
- Easy Video Player version: `0.2.13`

I add library from Gradel with custom Maven you say in issue because I have that problem too:
maven { url "https://dl.bintray.com/drummer-aidan/maven" }

now I get this error same in editor and in device (or emulator) they are both the same and say that.

[error.txt](https://github.com/afollestad/easy-video-player/files/524017/error.txt)

**Comment by tachang** [comment]
This is similar to the error I get. How do you troubleshoot?

**Comment by FDMpro** [comment]
@tachang with version 0.3.0 this problem is gone for me.

**Comment by tachang** [comment]
I am using Android Studio version 2.2.3.

The commit hash I am using is 8931c2cabff04a68169ff1b4d5bbc607fa5a9f6f

**Comment by tachang** [comment]
<img width="1439" alt="screen shot 2016-12-27 at 11 17 42 am" src="https://cloud.githubusercontent.com/assets/85011/21506591/264a3eda-cc26-11e6-9cce-55f64699aa82.png">

**Comment by afollestad** [comment]
Commit hash? You should be using the dependency through jCenter by version.

**Comment by afollestad** [comment]
Oh, and it's from the preview. That won't actually affect functionality in your app.

**Comment by tachang** [comment]
Is there a way to fix it?

**Comment by tachang** [comment]
I've narrowed it down to 

mPlayer = new MediaPlayer();

in

```
    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();

        setKeepScreenOn(true);

        mHandler = new Handler();
        mPlayer = new MediaPlayer();
```

**Comment by tachang** [comment]
Is it weird that instantiating it has a bunch of "stub" stuff with RuntimeException?

**Comment by tachang** [comment]
Is that what is causing the Preview error?

**Comment by afollestad** [comment]
All Android framework classes are stubs from your computer. That's not an error. 

The error is due to the fact that EasyVideoPlayer should not try to instantiate an instance of MediaPlayer while in edit mode (`isEditMode()` == true).
