### ISSUE TITLE
Failed to resolve: com.afollestad:easyvideoplayer:0.2.13 when using a library

### ISSUE THREAD

**Issue by mcaldas** [afollestad/easy-video-player#61]
- [ X ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ X ] I have verified that I am using the latest version of Easy Video Player.
- [ X ] I have given my issue a non-generic title.
- [ X ] I have read over the documentation (before asking questions on how to do something).
###### Include the following:
- Easy Video Player version: `0.2.13`
- Device OS version: `7.0`
- Device Manufacturer: `LG`
- Device Name: `Nexus 5x`

I know this issue has been covered a lot, but im having this issue in a library that implements the video player. The only way i found to make it work is adding `maven { url 'https://dl.bintray.com/drummer-aidan/maven'}` to the app that consumes my library, but that is not an option for production. Any suggestion how to fix this?

Thanks!

**Comment by tachang** [comment]
Why is it not an option for production?

**Comment by mcaldas** [comment]
Because we provide our library to third party customer, so I can't ask them to add on their project gradle every library we use.
Like all other libraries we use, they are resolved through mavenCentral or jcenter. Why it doesn't work like that here?

Thanks!

**Comment by afollestad** [comment]
It should resolve through jCenter, like all of my other libraries, for some reason this is the only one that doesn't work correctly.

**Comment by mcaldas** [comment]
Any chance of trying to fix it?
