### ISSUE TITLE
Error Inflating XML

### ISSUE THREAD

**Issue by DennyWeinberg** [afollestad/easy-video-player#64]
in some Clients I get the following error:

```java

Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.levionsoftware.photos/com.levionsoftware.photos.video_player.VideoPlayerActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.afollestad.easyvideoplayer.EasyVideoPlayer
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2200)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2250)
android.app.ActivityThread.access$800 (ActivityThread.java:139)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1200)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:136)
android.app.ActivityThread.main (ActivityThread.java:5105)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:792)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:608)
dalvik.system.NativeStart.main (NativeStart.java)
arrow_drop_down
Caused by android.view.InflateException: Binary XML file line #8: Error inflating class com.afollestad.easyvideoplayer.EasyVideoPlayer
arrow_drop_down
Caused by java.lang.reflect.InvocationTargetException:
arrow_drop_down
Caused by android.content.res.Resources$NotFoundException: File res/drawable/evp_action_restart.xml from drawable resource ID #0x7f02014d
arrow_drop_down
Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
```

**Comment by afollestad** [comment]
You didn't fill out the issue that template. 

What version or the library are you using?

**Comment by DennyWeinberg** [comment]
The latest one. compile 'com.afollestad:easyvideoplayer:0.2.13'

Android API: 19
Android-Betriebssystem: 4.4.2

**Comment by afollestad** [comment]
That's not the latest. This issue has already been fixed.

**Comment by DennyWeinberg** [comment]
OK sorry, thank you!

**Comment by DennyWeinberg** [comment]
Now I get this:

> Error:(2827, 44) No resource found that matches the given name (at 'android:textColorHint' with value '@color/hint_foreground_material_light').

> Error:(2827, 44) No resource found that matches the given name (at 'android:textColorHint' with value '@color/hint_foreground_material_light').

> Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by afollestad** [comment]
That isn't part of this library. 

You probably need to upgrade to AppCompat 25.0.0.

**Comment by DennyWeinberg** [comment]
Not possible - see stackoverflow...

**Comment by afollestad** [comment]
Well, I'm using this library with multiple production applications and have never run into any problems.

**Comment by afollestad** [comment]
I don't plan on downgrading this library from 25.0.0, though

**Comment by DennyWeinberg** [comment]
Hmm ok. Thank you. It's not your fault I think.
