### ISSUE TITLE
Publishing library at jcenter

### ISSUE THREAD

**Issue by zaolin** [afollestad/easy-video-player#7]
Hi,

seems that you forgot to publish the library at jcenter.

Best Regards
Zaolin

**Comment by afollestad** [comment]
No I didn't: https://bintray.com/bintray/jcenter?filterByPkgName=easy-video-player

**Comment by zaolin** [comment]
Take a look here: 

http://jcenter.bintray.com/com/afollestad/

Something went wrong.

**Comment by zaolin** [comment]
Normally gradle should find it easily via jcenter but the repo isn't exposed in bintray.
There was a bug report in the past. Maybe you should add to your README:

repositories {
maven { url "https://dl.bintray.com/drummer-aidan/maven" }
}

**Comment by michielibiza** [comment]
@afollestad Indeed, it's not yet at jcenter itself, only at "https://dl.bintray.com/drummer-aidan/maven". Maybe publish again? Or ask the jcenter guys for help?
