### ISSUE TITLE
Could this player play video only using youtube url ? 

### ISSUE THREAD

**Issue by vsingh-techracers** [afollestad/easy-video-player#76]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Easy Video Player.
- [ ] I have given my issue a non-generic title.
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Easy Video Player version: `x.x.x.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```
 
###### Reproduction Steps

1. 
2. 
3.

**Comment by afollestad** [comment]
If you get the URL to the actual file.

**Comment by PGMacDesign** [comment]
This is one of those things that isn't really an issue that is quickly solved by the Library Dev @vsingh-techracers 

When you have a youtube URL, IE: https://www.youtube.com/watch?v=7tzaWOdvGMw

That isn't the direct video url. What you need for this to work is the direct video URL of the actual file to view. his can be obtained or converted through conversion programs 
(IE, http://www.clipconverter.cc/) 

Which uses regular expressions to reverse engineer the URL:

https://r5---sn-25ge7ney.googlevideo.com/videoplayback?mn=sn-25ge7ney&mm=31&key=yt6&ip=91.121.13.168&pl=24&signature=9ED66FE84101E037F0B2B0EB62862E1F410E9401.16B9E1285535F9DFE16A2F51D242C7A1CB479E9F&initcwndbps=2082500&mv=m&mt=1482261751&ms=au&ipbits=0&requiressl=yes&sparams=dur,ei,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,nh,pl,ratebypass,requiressl,source,upn,expire&dur=518.989&id=o-AGFZ88_MQjEXyA1Yx2PXJr5vCff6pHRSewQkptvmi4-H&ei=QIZZWLzYIsy7cIjwn5gK&itag=22&nh=IgpwcjAxLnBhcjEwKgkxMjcuMC4wLjE&mime=video/mp4&expire=1482283680&lmt=1471447373855172&upn=u6BaqyZe434&source=youtube&ratebypass=yes&&title=Why+We+Haven%27t+Cured+Cancer

(Which is significantly longer). The short answer **(TL;TR)** is, if you want it to work with youtube videos, you will need a way to convert the youtube URL string to the actual video String and use that. Keep in mind though that Google changes this every once in a while and your code may or may not work all the time.
