### ISSUE TITLE
Problems in finding the lib through jcenter

### ISSUE THREAD

**Issue by franciscofranco** [afollestad/easy-video-player#9]
Error:Could not find com.afollestad:easyvideoplayer:0.2.8.

Doesn't work either with jcenter or jitpack. Is anything broken? Thanks.

**Comment by afollestad** [comment]
Something is indeed broken, I haven't been able to figure it out quite yet. Out of all of my libraries, this specific one is being stubborn with resolving through jCenter.

As a workaround (until I figure out the problem), you can add this to your repositories:

```gradle
repositories {
    ...
    maven { url "https://dl.bintray.com/drummer-aidan/maven" }
}
```

---

Love all of your apps, by the way :)

**Comment by franciscofranco** [comment]
Thanks for the quick reply! I'll try this out, I'm not 100% satisfied with ExoMedia lib.

Thanks for the nice words, I'm going to test this out for Focus. Love your work on these open source libs too, it helps me immensely to save time.

**Comment by afollestad** [comment]
No problem! I wasn't either; I tried using [ExoMedia](https://github.com/brianwernick/ExoMedia) in a few of my employer's apps and it had some weird behavioral issues. 

That's awesome, looking forward to hearing how it works out. Feel free to make PR's if you find any bugs or anything. Glad you find them useful!
